checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: 0

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 14d

npmPreapprovedPackages:
  - "@wix/*"

npmRegistryServer: "https://registry.npmjs.org"
