approvedGitRepositories:
  - '**'

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

enableTelemetry: 0

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 14d

npmPreapprovedPackages:
  - '@wix/*'
  - '@jay-framework/*'
