/**
 * Setup and references handlers for wix-data plugin (Design Log #87).
 *
 * Setup: Validates wix-server-client is configured; config auto-generated during init.
 * References: Generates collection schema data for agent discovery.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import type {
    PluginSetupContext,
    PluginSetupResult,
    PluginAgentKitContext,
    PluginAgentKitResult,
} from '@jay-framework/stack-server-runtime';
import { getService } from '@jay-framework/stack-server-runtime';
import { WIX_DATA_SERVICE_MARKER, type WixDataService } from './services/wix-data-service';

const CONFIG_FILE_NAME = 'wix-data.yaml';

// ============================================================================
// Setup handler (jay-stack setup) — config + validation only
// ============================================================================

export async function setupWixData(ctx: PluginSetupContext): Promise<PluginSetupResult> {
    const configPath = path.join(ctx.configDir, CONFIG_FILE_NAME);

    // wix-data depends on wix-server-client for credentials
    if (ctx.initError) {
        if (!fs.existsSync(configPath)) {
            return {
                status: 'needs-config',
                message:
                    'wix-data requires wix-server-client to be configured first. ' +
                    'Run: jay-stack setup wix-server-client',
            };
        }

        return {
            status: 'error',
            message: `Service init failed: ${ctx.initError.message}`,
        };
    }

    // Verify the data service is available
    try {
        getService(WIX_DATA_SERVICE_MARKER);
    } catch {
        return {
            status: 'error',
            message: 'WixDataService not available. Check initialization.',
        };
    }

    // Config was auto-generated by loadConfig during init
    const dataService = getService(WIX_DATA_SERVICE_MARKER) as WixDataService;
    const visibleCount = dataService.config.collections.filter((c) => c.visible).length;
    const totalCount = dataService.config.collections.length;

    return {
        status: 'configured',
        message: `${totalCount} collections found (${visibleCount} visible)`,
    };
}

// ============================================================================
// References handler (jay-stack agent-kit) — generate discovery data
// ============================================================================

export async function generateWixDataAgentKit(
    ctx: PluginAgentKitContext,
): Promise<PluginAgentKitResult> {
    // If plugin init failed, report the actual root cause
    if (ctx.initError) {
        throw new Error(`init failed: ${ctx.initError.message}`);
    }

    let dataService: WixDataService;
    try {
        dataService = getService(WIX_DATA_SERVICE_MARKER) as WixDataService;
    } catch {
        throw new Error('WixDataService not available. Run jay-stack setup first.');
    }

    // Ensure references directory exists
    fs.mkdirSync(ctx.referencesDir, { recursive: true });

    const config = dataService.config;
    const collectionSummaries: Array<{
        collectionId: string;
        visible: boolean;
        pathPrefix: string;
        slugField: string;
        fields: Array<{ key: string; displayName: string; type: string }>;
        references: Array<{ fieldName: string; targetCollection: string; isMulti: boolean }>;
        components: Record<string, boolean>;
    }> = [];

    for (const collConfig of config.collections) {
        const collection = await dataService.getCollection(collConfig.collectionId);
        if (!collection) continue;

        const fields = (collection.fields || []).map((f) => ({
            key: f.key || '',
            displayName: f.displayName || f.key || '',
            type: f.type || 'unknown',
        }));

        const referenceFields = (collection.fields || []).filter(
            (f) => f.type === 'REFERENCE' || f.type === 'MULTI_REFERENCE',
        );

        const references = referenceFields.map((f) => {
            const meta = f as {
                typeMetadata?: {
                    reference?: { referencedCollectionId?: string };
                    multiReference?: { referencedCollectionId?: string };
                };
            };
            return {
                fieldName: f.key || '',
                targetCollection:
                    meta.typeMetadata?.reference?.referencedCollectionId ||
                    meta.typeMetadata?.multiReference?.referencedCollectionId ||
                    'unknown',
                isMulti: f.type === 'MULTI_REFERENCE',
            };
        });

        const components: Record<string, boolean> = {};
        if (collConfig.components) {
            if (collConfig.components.itemPage) components.itemPage = true;
            if (collConfig.components.indexPage) components.indexPage = true;
            if (collConfig.components.categoryPage) components.categoryPage = true;
            if (collConfig.components.tableWidget) components.tableWidget = true;
            if (collConfig.components.cardWidget) components.cardWidget = true;
        }

        collectionSummaries.push({
            collectionId: collConfig.collectionId,
            visible: collConfig.visible ?? false,
            pathPrefix: collConfig.pathPrefix,
            slugField: collConfig.slugField,
            fields,
            references,
            components,
        });
    }

    const collectionsPath = path.join(ctx.referencesDir, 'collections.yaml');
    fs.writeFileSync(
        collectionsPath,
        yaml.dump(
            {
                _generated: new Date().toISOString(),
                _description:
                    'CMS collection schemas for agent discovery. Shows field types, references, and visibility.',
                totalCollections: collectionSummaries.length,
                visibleCollections: collectionSummaries.filter((c) => c.visible).length,
                collections: collectionSummaries,
            },
            { indent: 2, lineWidth: 120, noRefs: true },
        ),
        'utf-8',
    );

    return {
        agentKitCreated: [`agent-kit/references/${ctx.pluginName}/collections.yaml`],
        message: `${collectionSummaries.length} collections (${collectionSummaries.filter((c) => c.visible).length} visible)`,
    };
}
