import * as fs from 'node:fs';
import * as path from 'node:path';

import { load as loadYaml, dump as dumpYaml } from 'js-yaml';

import type { MediaAddMenuItem } from '../add-menu/media-items.js';
import { ADD_MENU_GENERATED_REL } from '../add-menu/write-add-menu-catalog.js';

export type CatalogYamlItem = MediaAddMenuItem;

export type MediaCatalogDocument = {
    items: CatalogYamlItem[];
    emptyFolders: string[][];
};

const CATALOG_HEADER =
    '# DO NOT EDIT BY HAND — regenerated by wix-media (setup / rebuild-index / incremental patch)\n\n';

export function folderPathKey(folderPath: string[]): string {
    return folderPath.join('\u0001');
}

export function normalizeFolderPath(folderPath: string[] | undefined): string[] {
    return folderPath ?? [];
}

export function catalogDocumentPath(projectRoot: string): string {
    return path.join(projectRoot, ADD_MENU_GENERATED_REL);
}

export function readMediaCatalogDocument(projectRoot: string): MediaCatalogDocument {
    const catalogPath = catalogDocumentPath(projectRoot);
    if (!fs.existsSync(catalogPath)) {
        return { items: [], emptyFolders: [] };
    }

    const parsed = loadYaml(fs.readFileSync(catalogPath, 'utf-8')) as {
        items?: CatalogYamlItem[];
        emptyFolders?: string[][];
    } | null;

    const items = parsed?.items ?? [];
    const emptyFolders = (parsed?.emptyFolders ?? [])
        .map((folderPath) => normalizeFolderPath(folderPath))
        .filter((folderPath) => folderPath.length > 0);

    return { items, emptyFolders };
}

export function writeMediaCatalogDocument(
    projectRoot: string,
    document: MediaCatalogDocument,
): string {
    const catalogPath = catalogDocumentPath(projectRoot);
    fs.mkdirSync(path.dirname(catalogPath), { recursive: true });

    const sortedItems = [...document.items].sort((left, right) =>
        left.title.localeCompare(right.title),
    );
    const sortedEmptyFolders = [...document.emptyFolders].sort((left, right) =>
        folderPathKey(left).localeCompare(folderPathKey(right)),
    );

    const body = dumpYaml(
        { emptyFolders: sortedEmptyFolders, items: sortedItems },
        { indent: 2, lineWidth: 120, noRefs: true },
    );
    fs.writeFileSync(catalogPath, CATALOG_HEADER + body, 'utf-8');

    return ADD_MENU_GENERATED_REL;
}

export function catalogItemIdForFile(fileId: string): string {
    return `wix-media:${fileId}`;
}
