name: wix-deploy

setup: setupWixDeploy

commands:
  - name: deploy
    command: deploy.jay-command
  - name: build-entry
    command: build-entry.jay-command
  - name: upload-backend
    command: upload-backend.jay-command
  - name: deploy-baas
    command: deploy-baas.jay-command
