name: wix-stores
# No module field for NPM packages - uses package main export by default

contracts:
  - name: product-page
    contract: product-page.jay-contract  # Export subpath (matches package.json exports)
    component: productPage  # Exported member name from index.ts
    description: Complete headless product page with server-side rendering and client interactivity
  - name: product-search
    contract: product-search.jay-contract
    component: productSearch
    description: Headless product search page
  - name: category-page
    contract: category-page.jay-contract
    component: categoryPage
    description: Category page listing the details of the category and the products within
  - name: category-list
    contract: category-list.jay-contract
    component: categoryList
    description: Category list listing the categories

# Server actions (named exports from main module)
actions:
  # Product actions
  - searchProducts
  - getProductBySlug
  - getCategories

# Plugin initialization uses makeJayInit pattern in lib/init.ts
# Export name defaults to 'init'
