import fs from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';
import type { FormAddMenuItem } from './form-items.js';

export const ADD_MENU_GENERATED_REL = 'agent-kit/aiditor/add-menu/wix-forms.generated.yaml';

export function writeGeneratedAddMenuCatalog(
    projectRoot: string,
    items: FormAddMenuItem[],
): string {
    const outputPath = path.join(projectRoot, ADD_MENU_GENERATED_REL);
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    const header =
        '# DO NOT EDIT BY HAND — regenerated by jay-stack agent-kit (wix-forms site forms)\n\n';
    const body = yaml.dump({ items }, { indent: 2, lineWidth: 120, noRefs: true });
    fs.writeFileSync(outputPath, header + body, 'utf-8');
    return ADD_MENU_GENERATED_REL;
}
