/**
 * jay-stack run wix-deploy/build-entry
 *
 * Reads route-manifest.json from the build backend dir, generates an entry
 * source with pre-imported plugins/actions + WixDataArtifactStore, and
 * bundles it with esbuild into a single entry.mjs (~3-5 MB).
 */

import { makeCliCommand, CONSOLE_CONTEXT } from '@jay-framework/fullstack-component';
import type { ConsoleContext } from '@jay-framework/fullstack-component';
import { DEFAULT_COLLECTION_ID, DEFAULT_CACHE_DIR } from '../constants.js';

interface BuildEntryInput {
    collectionId?: string;
    staticBaseUrl?: string;
    excludePlugins?: string;
}

interface RouteManifest {
    plugins: Array<{ name: string; packageName: string }>;
    actions: Array<{
        serverModule: string;
        packageName?: string;
        isPlugin: boolean;
        actionNames: string[];
    }>;
    routes: any[];
}

const DEFAULT_EXCLUDE_PLUGINS = ['aiditor', 'ui-kit', 'wix-deploy'];

function sortPluginsByDeps(plugins: Array<{ name: string; packageName: string }>) {
    const priorityPackages = ['@jay-framework/wix-server-client'];
    const sorted: typeof plugins = [];
    for (const pkg of priorityPackages) {
        const p = plugins.find((p) => p.packageName === pkg);
        if (p) sorted.push(p);
    }
    for (const p of plugins) {
        if (!sorted.includes(p)) sorted.push(p);
    }
    return sorted;
}

function generateStubContents(modulePath: string): string {
    const throwStub = '() => { throw new Error("build-time only"); }';
    const stubs: Record<string, string> = {
        '@jay-framework/compiler-jay-html': [
            'export default {};',
            `export const parseJayFile = ${throwStub};`,
            `export const JAY_IMPORT_RESOLVER = {};`,
            `export const generateServerElementFile = ${throwStub};`,
            `export const injectHeadfullFSTemplates = ${throwStub};`,
            `export const discoverHeadlessInstances = ${throwStub};`,
            `export const assignCoordinatesToJayHtml = ${throwStub};`,
            `export const parseAction = ${throwStub};`,
            `export const parseContract = ${throwStub};`,
        ].join('\n'),
        '@jay-framework/compiler-shared': [
            'export default {};',
            `export const checkValidationErrors = (x) => x;`,
            `export const formatCode = (code) => code;`,
        ].join('\n'),
        '@jay-framework/compiler-jay-stack': [
            'export default {};',
            `export const jayStackCompiler = ${throwStub};`,
        ].join('\n'),
        '@jay-framework/compiler-analyze-exported-types': [
            'export default {};',
            `export const extractActionsFromSource = ${throwStub};`,
        ].join('\n'),
        '@jay-framework/compiler': [
            'export default {};',
            `export const jayRuntime = ${throwStub};`,
        ].join('\n'),
    };
    return stubs[modulePath] || 'export default {};';
}

function generateEntrySource(
    plugins: Array<{ name: string; packageName: string }>,
    actionPackages: string[],
    serverElements: Array<{ relativePath: string; absolutePath: string }>,
    collectionId: string,
    staticBaseUrl: string,
    version: number,
): string {
    const pluginImports = plugins.map(
        (p, i) => `import { init as pluginInit_${i} } from '${p.packageName}';`,
    );
    const moduleImports = plugins.map(
        (p, i) => `import * as pluginModule_${i} from '${p.packageName}';`,
    );
    const seImports = serverElements.map(
        (se, i) => `import * as serverElement_${i} from '${se.absolutePath}';`,
    );
    const pluginsArray = plugins.map((p, i) => `    { name: '${p.name}', init: pluginInit_${i} },`);
    const registryEntries = [
        ...plugins.map((p, i) => `    '${p.packageName}': pluginModule_${i},`),
        ...serverElements.map((se, i) => `    '${se.relativePath}': serverElement_${i},`),
    ];
    const actionsArray = actionPackages.map((pkg) => {
        const idx = plugins.findIndex((p) => p.packageName === pkg);
        return `    { module: pluginModule_${idx}, name: '${pkg}' },`;
    });

    return `// Auto-generated BaaS entry — do not edit
// Generated by @jay-framework/wix-deploy build-entry

// Plugin imports (init + full modules for page-parts resolution)
${pluginImports.join('\n')}
${moduleImports.join('\n')}

// Server element imports (bundled with ssr-runtime)
${seImports.join('\n')}

// Framework imports
import {
    matchRequest,
    fetchPageRequest,
    fetchActionRequest,
    isActionRequest,
    initializeServicesFromModules,
    registerActionsFromModules,
    FilesystemArtifactStore,
} from '@jay-framework/production-server/serve';
import { parseCookies, getService } from '@jay-framework/stack-server-runtime';
import { WIX_CLIENT_SERVICE } from '@jay-framework/wix-server-client';
import { WixDataArtifactStore } from '@jay-framework/wix-deploy/artifact-store';

// Module registry — npm packages + server elements (all bundled by esbuild)
const MODULE_REGISTRY = {
${registryEntries.join('\n')}
};

// Configuration
const COLLECTION_ID = process.env.JAY_COLLECTION_ID || '${collectionId}';
const STATIC_BASE_URL = process.env.STATIC_BASE_URL || '${staticBaseUrl}';
const VERSION = parseInt(process.env.JAY_BUILD_VERSION || '${version}', 10);
const LOCAL_BACKEND_DIR = process.env.JAY_BACKEND_DIR || '';

let artifacts;
let initialized = false;
let initError = null;

async function initialize() {
    if (initialized) return;

    // Set CWD to entry.mjs dir so config/.wix.yaml is found by wix-server-client
    const entryDir = new URL('.', import.meta.url).pathname;
    if (entryDir && process.cwd() !== entryDir) {
        try { process.chdir(entryDir); } catch {}
    }
    console.log('[BaaS] CWD:', process.cwd());

    // BaaS skips dotfiles during upload — copy wix.yaml to .wix.yaml if needed
    const fs = await import('node:fs');
    const configDir = process.cwd() + '/config';
    const dotYaml = configDir + '/.wix.yaml';
    const plainYaml = configDir + '/wix.yaml';
    if (!fs.existsSync(dotYaml) && fs.existsSync(plainYaml)) {
        fs.copyFileSync(plainYaml, dotYaml);
        console.log('[BaaS] Copied config/wix.yaml to config/.wix.yaml');
    }

    // Initialize plugins first — wix-server-client reads config/.wix.yaml and creates WixClient
    console.log('[BaaS] Initializing plugins...');
    await initializeServicesFromModules([
${pluginsArray.join('\n')}
    ], 'BaaS');

    // Register actions
    console.log('[BaaS] Registering actions...');
    await registerActionsFromModules([
${actionsArray.join('\n')}
    ]);

    // Create artifact store — uses the WixClient that wix-server-client just initialized
    if (LOCAL_BACKEND_DIR) {
        console.log('[BaaS] Using filesystem artifact store:', LOCAL_BACKEND_DIR);
        artifacts = new FilesystemArtifactStore(LOCAL_BACKEND_DIR);
    } else {
        console.log('[BaaS] Creating WixDataArtifactStore...');
        const wixClientService = getService(WIX_CLIENT_SERVICE);
        console.log('[BaaS] WixClientService:', wixClientService ? 'found' : 'MISSING');
        artifacts = new WixDataArtifactStore({
            wixClient: wixClientService,
            collectionId: COLLECTION_ID,
            version: VERSION,
            cacheDir: '${DEFAULT_CACHE_DIR}',
            moduleRegistry: MODULE_REGISTRY,
        });
        console.log('[BaaS] Loading eager files...');
        await artifacts.loadEagerFiles();
    }

    initialized = true;
    console.log('[BaaS] Initialization complete');
}

function errorPage(title, err, path) {
    const html = '<!doctype html><html><head><meta charset="UTF-8"><title>' + title + '</title>'
        + '<style>body{font-family:monospace;max-width:800px;margin:40px auto;padding:0 20px}'
        + 'h1{color:#c00}pre{background:#f5f5f5;padding:16px;overflow-x:auto;border-radius:4px}'
        + '.path{color:#666}</style></head><body>'
        + '<h1>' + title + '</h1>'
        + '<p class="path">' + path + '</p>'
        + '<p><strong>' + (err.message || '') + '</strong></p>'
        + '<pre>' + (err.stack || '') + '</pre>'
        + '</body></html>';
    return new Response(html, { status: 500, headers: { 'Content-Type': 'text/html' } });
}

async function handler(request) {
    const url = new URL(request.url);

    // Diagnostic endpoint — runs before init
    if (url.pathname === '/_jay/debug') {
        const fs = await import('node:fs');
        const entryDir = new URL('.', import.meta.url).pathname;
        const info = {
            cwd: process.cwd(),
            entryUrl: import.meta.url,
            entryDir,
            initialized,
            hasArtifacts: !!artifacts,
            initError: initError?.message || null,
        };
        try { info.cwdFiles = fs.readdirSync(process.cwd()); } catch (e) { info.cwdFiles = e.message; }
        try { info.configDirFiles = fs.readdirSync(process.cwd() + '/config'); } catch (e) { info.configDirFiles = e.message; }
        try { info.entryDirFiles = fs.readdirSync(entryDir); } catch (e) { info.entryDirFiles = e.message; }
        try { info.entryConfigFiles = fs.readdirSync(entryDir + '/config'); } catch (e) { info.entryConfigFiles = e.message; }
        try { info.userCodeFiles = fs.readdirSync('/user-code'); } catch (e) { info.userCodeFiles = e.message; }
        try { info.userCodeConfigFiles = fs.readdirSync('/user-code/config'); } catch (e) { info.userCodeConfigFiles = e.message; }
        return new Response(JSON.stringify(info, null, 2), { headers: { 'Content-Type': 'application/json' } });
    }

    try {
        await initialize();
    } catch (e) {
        if (!initError) {
            initError = e;
            console.error('[BaaS] INIT FAILED:', e.message, e.stack);
        }
        return errorPage('Initialization Failed', e, url.pathname);
    }

    try {
        if (isActionRequest(url.pathname)) return fetchActionRequest(request);

        const manifest = await artifacts.readManifest();
        const match = matchRequest(manifest, url.pathname);
        if (!match) return new Response('Not Found', { status: 404 });

        // Ensure lazy page files are on disk before rendering
        const pagePath = match.instance.cachePath || match.instance.preRenderedPath;
        if (artifacts.ensurePageFiles && pagePath) {
            await artifacts.ensurePageFiles(pagePath);
        }

        const cookies = parseCookies(request.headers.get('cookie') || '');
        return fetchPageRequest(match, manifest, url, artifacts, STATIC_BASE_URL, cookies);
    } catch (e) {
        console.error('[BaaS] REQUEST FAILED:', url.pathname, e.message, e.stack);
        return errorPage('Request Failed', e, url.pathname);
    }
}

export default { fetch: handler };
export { handler as fetch };
`;
}

function generateServeSource(frontendDir: string, backendDir: string): string {
    const lines = [
        '#!/usr/bin/env node',
        '// Local test server for the BaaS entry — run with: node dist/serve.mjs',
        'import http from "node:http";',
        'import fs from "node:fs";',
        'import path from "node:path";',
        'import { Readable } from "node:stream";',
        '',
        'process.env.STATIC_BASE_URL = process.env.STATIC_BASE_URL || "/";',
        `process.env.JAY_BACKEND_DIR = process.env.JAY_BACKEND_DIR || "${backendDir}";`,
        'const entry = await import("./entry.mjs");',
        'const handler = entry.default?.fetch || entry.fetch;',
        'const PORT = parseInt(process.env.PORT || "4000", 10);',
        `const FRONTEND_DIR = "${frontendDir}";`,
        '',
        'const MIME = {',
        '    ".js": "application/javascript", ".mjs": "application/javascript",',
        '    ".css": "text/css", ".html": "text/html", ".json": "application/json",',
        '    ".png": "image/png", ".jpg": "image/jpeg", ".svg": "image/svg+xml",',
        '    ".woff2": "font/woff2", ".woff": "font/woff",',
        '};',
        '',
        'function serveStatic(pathname, res) {',
        '    const fp = path.join(FRONTEND_DIR, pathname);',
        '    if (!fs.existsSync(fp) || !fs.statSync(fp).isFile()) return false;',
        '    res.writeHead(200, { "Content-Type": MIME[path.extname(fp)] || "application/octet-stream" });',
        '    fs.createReadStream(fp).pipe(res);',
        '    return true;',
        '}',
        '',
        'http.createServer(async (req, res) => {',
        '    const url = new URL(req.url, "http://" + req.headers.host);',
        '    if (serveStatic(url.pathname, res)) return;',
        '    const headers = new Headers();',
        '    for (const [k, v] of Object.entries(req.headers)) {',
        '        if (v) headers.set(k, Array.isArray(v) ? v.join(", ") : v);',
        '    }',
        '    const init = { method: req.method, headers };',
        '    if (req.method !== "GET" && req.method !== "HEAD") {',
        '        init.body = Readable.toWeb(req); init.duplex = "half";',
        '    }',
        '    try {',
        '        const response = await handler(new Request(url, init));',
        '        const rh = {}; response.headers.forEach((v, k) => { rh[k] = v; });',
        '        res.writeHead(response.status, rh);',
        '        if (response.body) {',
        '            const reader = response.body.getReader();',
        '            while (true) { const { done, value } = await reader.read(); if (done) break; res.write(value); }',
        '        }',
        '        res.end();',
        '    } catch (err) { console.error("Handler error:", err); res.writeHead(500); res.end("Internal Server Error"); }',
        '}).listen(PORT, () => {',
        '    console.log("Local test server at http://localhost:" + PORT);',
        '    console.log("Frontend: " + FRONTEND_DIR);',
        '});',
    ];
    return lines.join('\n') + '\n';
}

export const buildEntry = makeCliCommand('build-entry')
    .withServices(CONSOLE_CONTEXT)
    .withHandler(async (input: BuildEntryInput, ctx: ConsoleContext) => {
        const fs = await import('node:fs');
        const path = await import('node:path');
        const { createRequire } = await import('node:module');

        const buildDir = ctx.build.backend;
        const outFile = path.resolve(ctx.projectRoot, 'dist/entry.mjs');

        const collectionId = input.collectionId || DEFAULT_COLLECTION_ID;
        const staticBaseUrl = input.staticBaseUrl || '/';
        const userExcludes = input.excludePlugins?.split(',') || [];
        const excludePlugins = [...DEFAULT_EXCLUDE_PLUGINS, ...userExcludes];

        ctx.log(`Build dir: ${buildDir}`);
        ctx.log(`Output: ${outFile}`);

        const manifestPath = path.join(buildDir, 'route-manifest.json');
        if (!fs.existsSync(manifestPath)) {
            ctx.error(`route-manifest.json not found at ${manifestPath}`);
            ctx.error('Run jay-stack build first.');
            return { success: false };
        }

        const manifest: RouteManifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

        // Read version from build-metadata.json
        const metadataPath = path.join(buildDir, 'build-metadata.json');
        let version = 1;
        if (fs.existsSync(metadataPath)) {
            const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
            version = metadata.version || 1;
        }

        const filteredPlugins = manifest.plugins.filter(
            (p) => !excludePlugins.includes(p.name) && !excludePlugins.includes(p.packageName),
        );
        // wix-server-client must init before plugins that depend on it
        const plugins = sortPluginsByDeps(filteredPlugins);
        const pluginPackages = new Set(plugins.map((p) => p.packageName));
        const actionPackages = manifest.actions
            .filter((a) => a.isPlugin && a.packageName && pluginPackages.has(a.packageName!))
            .map((a) => a.packageName!)
            .filter((v, i, arr) => arr.indexOf(v) === i);

        // Collect unique server element paths from routes
        const seSet = new Set<string>();
        for (const route of manifest.routes) {
            if (route.serverElementPath) seSet.add(route.serverElementPath);
        }
        const serverElements = [...seSet].map((rel) => ({
            relativePath: rel,
            absolutePath: path.join(buildDir, rel),
        }));

        ctx.log(`Version: ${version}`);
        ctx.log(`Plugins: ${plugins.map((p) => p.name).join(', ')}`);
        ctx.log(`Action packages: ${actionPackages.join(', ')}`);
        ctx.log(`Server elements: ${serverElements.length} routes`);

        const entrySource = generateEntrySource(
            plugins,
            actionPackages,
            serverElements,
            collectionId,
            staticBaseUrl,
            version,
        );

        const entryDir = path.dirname(outFile);
        fs.mkdirSync(entryDir, { recursive: true });
        const tempEntryPath = path.join(entryDir, '.entry.generated.mjs');
        fs.writeFileSync(tempEntryPath, entrySource, 'utf8');

        // Build-time-only dep stubs
        const stubs = [
            '@jay-framework/compiler-jay-html',
            '@jay-framework/compiler-shared',
            '@jay-framework/compiler-analyze-exported-types',
            '@jay-framework/compiler-jay-stack',
            '@jay-framework/compiler',
            '@jay-framework/rollup-plugin',
            '@jay-framework/vite-plugin',
            'typescript',
            'prettier',
            'vite',
            'lightningcss',
            'fsevents',
        ];
        const stubFilter = new RegExp(
            '^(' + stubs.map((s) => s.replace(/[/.]/g, '\\$&')).join('|') + ')$',
        );

        const stubBuildDepsPlugin = {
            name: 'stub-build-deps',
            setup(build: any) {
                build.onResolve({ filter: stubFilter }, (args: any) => ({
                    path: args.path,
                    namespace: 'stub',
                }));
                build.onLoad({ filter: /.*/, namespace: 'stub' }, (args: any) => ({
                    contents: generateStubContents(args.path),
                    loader: 'js',
                }));
            },
        };

        // Resolve sub-path imports
        const require = createRequire(import.meta.url);
        const resolveAliasPlugin = {
            name: 'resolve-aliases',
            setup(build: any) {
                build.onResolve({ filter: /^@jay-framework\/production-server\/serve$/ }, () => {
                    return { path: require.resolve('@jay-framework/production-server/serve') };
                });
                build.onResolve({ filter: /^@jay-framework\/wix-deploy\/artifact-store$/ }, () => {
                    return { path: require.resolve('@jay-framework/wix-deploy/artifact-store') };
                });
            },
        };

        const esbuild = await import('esbuild');
        const result = await esbuild.build({
            entryPoints: [tempEntryPath],
            bundle: true,
            format: 'esm',
            platform: 'node',
            target: 'node20',
            outfile: outFile,
            external: ['node:*'],
            banner: {
                js: 'import { createRequire as __bundleCreateRequire } from "node:module";const require = __bundleCreateRequire(import.meta.url);',
            },
            plugins: [resolveAliasPlugin, stubBuildDepsPlugin],
            minify: false,
            treeShaking: true,
            logLevel: 'warning',
            metafile: true,
        });

        fs.rmSync(tempEntryPath, { force: true });

        // Patch runtime require() calls for build-time-only modules
        // These use createRequire(import.meta.url)("typescript") which bypasses esbuild stubs
        const runtimeStubs = ['typescript', 'prettier', 'lightningcss'];
        let patched = fs.readFileSync(outFile, 'utf8');
        let patchCount = 0;
        for (const mod of runtimeStubs) {
            const pattern = new RegExp(`(\\w+)\\("${mod}"\\)`, 'g');
            const before = patched;
            patched = patched.replace(pattern, '({})');
            if (patched !== before) patchCount++;
        }
        if (patchCount > 0) {
            fs.writeFileSync(outFile, patched);
            ctx.log(`Patched ${patchCount} runtime require() calls for build-time modules`);
        }

        const stat = fs.statSync(outFile);
        const sizeMB = (stat.size / 1024 / 1024).toFixed(1);
        ctx.log(`Done: ${outFile} (${sizeMB} MB)`);

        if (result.metafile) {
            ctx.log(`Bundled ${Object.keys(result.metafile.inputs).length} input files`);
            fs.writeFileSync(
                outFile.replace(/\.mjs$/, '.meta.json'),
                JSON.stringify(result.metafile),
            );
        }

        // Copy config/.wix.yaml to dist/ so wix-server-client can find it on BaaS
        // Also copy as wix.yaml (without dot) in case the CLI skips dotfiles
        const wixConfigSrc = path.join(ctx.projectRoot, 'config', '.wix.yaml');
        if (fs.existsSync(wixConfigSrc)) {
            const configDir = path.join(entryDir, 'config');
            fs.mkdirSync(configDir, { recursive: true });
            fs.copyFileSync(wixConfigSrc, path.join(configDir, '.wix.yaml'));
            fs.copyFileSync(wixConfigSrc, path.join(configDir, 'wix.yaml'));
            ctx.log(`Copied config/.wix.yaml to dist/config/`);
        } else {
            ctx.warn(
                `config/.wix.yaml not found — wix-server-client init will fail on BaaS unless WIX_API_KEY env vars are set`,
            );
        }

        // Generate serve.mjs for local testing
        const serveFile = path.join(entryDir, 'serve.mjs');
        fs.writeFileSync(serveFile, generateServeSource(ctx.build.frontend, buildDir));
        ctx.log(`Generated ${serveFile} — run with: node dist/serve.mjs`);

        return { success: true, outFile, sizeMB };
    });
