/**
 * jay-stack run wix-deploy/build-entry
 *
 * Reads route-manifest.json from the build backend dir, generates an entry
 * source with pre-imported plugins/actions + WixDataArtifactStore, and
 * bundles it with esbuild into a single entry.mjs (~3-5 MB).
 */

import { makeCliCommand, CONSOLE_CONTEXT } from '@jay-framework/fullstack-component';
import type { ConsoleContext } from '@jay-framework/fullstack-component';
import { DEFAULT_COLLECTION_ID, DEFAULT_CACHE_DIR } from '../constants.js';

interface BuildEntryInput {
    collectionId?: string;
    staticBaseUrl?: string;
    excludePlugins?: string;
}

interface RouteManifest {
    plugins: Array<{ name: string; packageName: string }>;
    actions: Array<{
        serverModule: string;
        packageName?: string;
        isPlugin: boolean;
        actionNames: string[];
    }>;
    routes: any[];
}

function generateStubContents(modulePath: string): string {
    const throwStub = '() => { throw new Error("build-time only"); }';
    const stubs: Record<string, string> = {
        '@jay-framework/compiler-jay-html': [
            'export default {};',
            `export const parseJayFile = ${throwStub};`,
            `export const JAY_IMPORT_RESOLVER = {};`,
            `export const generateServerElementFile = ${throwStub};`,
            `export const injectHeadfullFSTemplates = ${throwStub};`,
            `export const discoverHeadlessInstances = ${throwStub};`,
            `export const assignCoordinatesToJayHtml = ${throwStub};`,
            `export const parseAction = ${throwStub};`,
            `export const parseContract = ${throwStub};`,
        ].join('\n'),
        '@jay-framework/compiler-shared': [
            'export default {};',
            `export const checkValidationErrors = (x) => x;`,
            `export const formatCode = (code) => code;`,
        ].join('\n'),
        '@jay-framework/compiler-jay-stack': [
            'export default {};',
            `export const jayStackCompiler = ${throwStub};`,
        ].join('\n'),
        '@jay-framework/compiler-analyze-exported-types': [
            'export default {};',
            `export const extractActionsFromSource = ${throwStub};`,
        ].join('\n'),
        '@jay-framework/compiler': [
            'export default {};',
            `export const jayRuntime = ${throwStub};`,
        ].join('\n'),
    };
    return stubs[modulePath] || 'export default {};';
}

function generateEntrySource(
    plugins: Array<{ name: string; packageName: string }>,
    actionPackages: string[],
    collectionId: string,
    staticBaseUrl: string,
    version: number,
): string {
    const pluginImports = plugins.map(
        (p, i) => `import { init as pluginInit_${i} } from '${p.packageName}';`,
    );
    const actionImports = actionPackages.map(
        (pkg, i) => `import * as actionModule_${i} from '${pkg}';`,
    );
    const pluginsArray = plugins.map(
        (p, i) => `    { name: '${p.name}', init: pluginInit_${i} },`,
    );
    const actionsArray = actionPackages.map(
        (pkg, i) => `    { module: actionModule_${i}, name: '${pkg}' },`,
    );

    return `// Auto-generated BaaS entry — do not edit
// Generated by @jay-framework/wix-deploy build-entry

// Plugin init imports
${pluginImports.join('\n')}

// Action module imports
${actionImports.join('\n')}

// Framework imports
import {
    matchRequest,
    fetchPageRequest,
    fetchActionRequest,
    isActionRequest,
    initializeServicesFromModules,
    registerActionsFromModules,
} from '@jay-framework/production-server/serve';
import { parseCookies } from '@jay-framework/stack-server-runtime';

// BaaS adapter
import { WixDataArtifactStore } from '@jay-framework/wix-deploy/artifact-store';
import { createClient, ApiKeyStrategy } from '@wix/sdk';

// Configuration from environment
const COLLECTION_ID = process.env.JAY_COLLECTION_ID || '${collectionId}';
const STATIC_BASE_URL = process.env.STATIC_BASE_URL || '${staticBaseUrl}';
const VERSION = parseInt(process.env.JAY_BUILD_VERSION || '${version}', 10);
const API_KEY = process.env.WIX_API_KEY || '';
const SITE_ID = process.env.WIX_SITE_ID || '';

// Wix client for data collection access
const wixClient = createClient({
    auth: ApiKeyStrategy({ apiKey: API_KEY, siteId: SITE_ID }),
    modules: {},
});

// Artifact store
const artifacts = new WixDataArtifactStore({
    wixClient,
    collectionId: COLLECTION_ID,
    version: VERSION,
    cacheDir: '${DEFAULT_CACHE_DIR}',
});

// Initialization state
let initialized = false;

async function initialize() {
    if (initialized) return;
    initialized = true;

    // Load eager files from data collection
    await artifacts.loadEagerFiles();

    // Initialize plugin services
    await initializeServicesFromModules([
${pluginsArray.join('\n')}
    ], 'BaaS');

    // Register actions
    await registerActionsFromModules([
${actionsArray.join('\n')}
    ]);

    console.log('[BaaS] Initialization complete');
}

// Fetch handler
async function handler(request) {
    await initialize();

    const url = new URL(request.url);

    // Actions
    if (isActionRequest(url.pathname)) {
        return fetchActionRequest(request);
    }

    // Page requests
    const manifest = await artifacts.readManifest();
    const match = matchRequest(manifest, url.pathname);

    if (!match) {
        return new Response('Not Found', { status: 404 });
    }

    const cookies = parseCookies(request.headers.get('cookie') || '');
    return fetchPageRequest(match, manifest, url, artifacts, STATIC_BASE_URL, cookies);
}

export default { fetch: handler };
export { handler as fetch };
`;
}

function generateServeSource(frontendDir: string): string {
    const lines = [
        '#!/usr/bin/env node',
        '// Local test server for the BaaS entry — run with: node dist/serve.mjs',
        'import http from "node:http";',
        'import fs from "node:fs";',
        'import path from "node:path";',
        'import { Readable } from "node:stream";',
        '',
        'const entry = await import("./entry.mjs");',
        'const handler = entry.default?.fetch || entry.fetch;',
        'const PORT = parseInt(process.env.PORT || "4000", 10);',
        `const FRONTEND_DIR = "${frontendDir}";`,
        '',
        'const MIME = {',
        '    ".js": "application/javascript", ".mjs": "application/javascript",',
        '    ".css": "text/css", ".html": "text/html", ".json": "application/json",',
        '    ".png": "image/png", ".jpg": "image/jpeg", ".svg": "image/svg+xml",',
        '    ".woff2": "font/woff2", ".woff": "font/woff",',
        '};',
        '',
        'function serveStatic(pathname, res) {',
        '    const fp = path.join(FRONTEND_DIR, pathname);',
        '    if (!fs.existsSync(fp) || !fs.statSync(fp).isFile()) return false;',
        '    res.writeHead(200, { "Content-Type": MIME[path.extname(fp)] || "application/octet-stream" });',
        '    fs.createReadStream(fp).pipe(res);',
        '    return true;',
        '}',
        '',
        'http.createServer(async (req, res) => {',
        '    const url = new URL(req.url, "http://" + req.headers.host);',
        '    if (serveStatic(url.pathname, res)) return;',
        '    const headers = new Headers();',
        '    for (const [k, v] of Object.entries(req.headers)) {',
        '        if (v) headers.set(k, Array.isArray(v) ? v.join(", ") : v);',
        '    }',
        '    const init = { method: req.method, headers };',
        '    if (req.method !== "GET" && req.method !== "HEAD") {',
        '        init.body = Readable.toWeb(req); init.duplex = "half";',
        '    }',
        '    try {',
        '        const response = await handler(new Request(url, init));',
        '        const rh = {}; response.headers.forEach((v, k) => { rh[k] = v; });',
        '        res.writeHead(response.status, rh);',
        '        if (response.body) {',
        '            const reader = response.body.getReader();',
        '            while (true) { const { done, value } = await reader.read(); if (done) break; res.write(value); }',
        '        }',
        '        res.end();',
        '    } catch (err) { console.error("Handler error:", err); res.writeHead(500); res.end("Internal Server Error"); }',
        '}).listen(PORT, () => {',
        '    console.log("Local test server at http://localhost:" + PORT);',
        '    console.log("Frontend: " + FRONTEND_DIR);',
        '});',
    ];
    return lines.join('\n') + '\n';
}

export const buildEntry = makeCliCommand('build-entry')
    .withServices(CONSOLE_CONTEXT)
    .withHandler(async (input: BuildEntryInput, ctx: ConsoleContext) => {
        const fs = await import('node:fs');
        const path = await import('node:path');
        const { createRequire } = await import('node:module');

        const buildDir = ctx.build.backend;
        const outFile = path.resolve(ctx.projectRoot, 'dist/entry.mjs');

        const collectionId = input.collectionId || DEFAULT_COLLECTION_ID;
        const staticBaseUrl = input.staticBaseUrl || '/';
        const excludePlugins = input.excludePlugins?.split(',') || [];

        ctx.log(`Build dir: ${buildDir}`);
        ctx.log(`Output: ${outFile}`);

        const manifestPath = path.join(buildDir, 'route-manifest.json');
        if (!fs.existsSync(manifestPath)) {
            ctx.error(`route-manifest.json not found at ${manifestPath}`);
            ctx.error('Run jay-stack build first.');
            return { success: false };
        }

        const manifest: RouteManifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

        // Read version from build-metadata.json
        const metadataPath = path.join(buildDir, 'build-metadata.json');
        let version = 1;
        if (fs.existsSync(metadataPath)) {
            const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
            version = metadata.version || 1;
        }

        const plugins = manifest.plugins.filter(
            p => !excludePlugins.includes(p.name) && !excludePlugins.includes(p.packageName),
        );
        const pluginPackages = new Set(plugins.map(p => p.packageName));
        const actionPackages = manifest.actions
            .filter(a => a.isPlugin && a.packageName && pluginPackages.has(a.packageName!))
            .map(a => a.packageName!)
            .filter((v, i, arr) => arr.indexOf(v) === i);

        ctx.log(`Version: ${version}`);
        ctx.log(`Plugins: ${plugins.map(p => p.name).join(', ')}`);
        ctx.log(`Action packages: ${actionPackages.join(', ')}`);

        const entrySource = generateEntrySource(plugins, actionPackages, collectionId, staticBaseUrl, version);

        const entryDir = path.dirname(outFile);
        fs.mkdirSync(entryDir, { recursive: true });
        const tempEntryPath = path.join(entryDir, '.entry.generated.mjs');
        fs.writeFileSync(tempEntryPath, entrySource, 'utf8');

        // Build-time-only dep stubs
        const stubs = [
            '@jay-framework/compiler-jay-html',
            '@jay-framework/compiler-shared',
            '@jay-framework/compiler-analyze-exported-types',
            '@jay-framework/compiler-jay-stack',
            '@jay-framework/compiler',
            '@jay-framework/rollup-plugin',
            '@jay-framework/vite-plugin',
            'typescript', 'prettier', 'vite', 'lightningcss', 'fsevents',
        ];
        const stubFilter = new RegExp(
            '^(' + stubs.map(s => s.replace(/[/.]/g, '\\$&')).join('|') + ')$',
        );

        const stubBuildDepsPlugin = {
            name: 'stub-build-deps',
            setup(build: any) {
                build.onResolve({ filter: stubFilter }, (args: any) => ({
                    path: args.path, namespace: 'stub',
                }));
                build.onLoad({ filter: /.*/, namespace: 'stub' }, (args: any) => ({
                    contents: generateStubContents(args.path), loader: 'js',
                }));
            },
        };

        // Resolve sub-path imports
        const require = createRequire(import.meta.url);
        const resolveAliasPlugin = {
            name: 'resolve-aliases',
            setup(build: any) {
                build.onResolve({ filter: /^@jay-framework\/production-server\/serve$/ }, () => {
                    const pkgDir = path.dirname(require.resolve('@jay-framework/production-server/package.json'));
                    return { path: path.join(pkgDir, 'dist/serve-index.js') };
                });
                build.onResolve({ filter: /^@jay-framework\/wix-deploy\/artifact-store$/ }, () => {
                    return { path: path.resolve(path.dirname(new URL(import.meta.url).pathname), '../artifact-store.ts') };
                });
            },
        };

        const esbuild = await import('esbuild');
        const result = await esbuild.build({
            entryPoints: [tempEntryPath],
            bundle: true,
            format: 'esm',
            platform: 'node',
            target: 'node20',
            outfile: outFile,
            external: ['node:*'],
            banner: {
                js: 'import { createRequire as __bundleCreateRequire } from "node:module";const require = __bundleCreateRequire(import.meta.url);',
            },
            plugins: [resolveAliasPlugin, stubBuildDepsPlugin],
            minify: false,
            treeShaking: true,
            logLevel: 'warning',
            metafile: true,
        });

        fs.rmSync(tempEntryPath, { force: true });

        const stat = fs.statSync(outFile);
        const sizeMB = (stat.size / 1024 / 1024).toFixed(1);
        ctx.log(`Done: ${outFile} (${sizeMB} MB)`);

        if (result.metafile) {
            ctx.log(`Bundled ${Object.keys(result.metafile.inputs).length} input files`);
            fs.writeFileSync(outFile.replace(/\.mjs$/, '.meta.json'), JSON.stringify(result.metafile));
        }

        // Generate serve.mjs for local testing
        const serveFile = path.join(entryDir, 'serve.mjs');
        const frontendDir = ctx.build.frontend;
        fs.writeFileSync(serveFile, generateServeSource(frontendDir));
        ctx.log(`Generated ${serveFile} — run with: node dist/serve.mjs`);

        return { success: true, outFile, sizeMB };
    });
