/**
 * Setup handler for wix-stores plugin (Design Log #87, #10).
 *
 * Validates that wix-server-client is configured.
 * Creates config/.wix-stores.yaml with example category prefix config if missing.
 * Generates category tree reference for agent discovery.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import * as yaml from 'js-yaml';
import type {
    PluginSetupContext,
    PluginSetupResult,
    PluginReferencesContext,
    PluginReferencesResult,
} from '@jay-framework/stack-server-runtime';
import { getService } from '@jay-framework/stack-server-runtime';
import { WIX_STORES_SERVICE_MARKER, type WixStoresService } from './services/wix-stores-service';
import { queryCategories as queryCategoriesApi } from './wix-apis/index.js';
import type { DataExtensionSchema } from './utils/data-extension-schema';
import { buildCategoryAddMenuItems, type CategoryTreeNode } from './add-menu/category-items.js';
import { copyAiditorAddMenuThumbnails } from './add-menu/copy-aiditor-thumbnails.js';
import { loadWixStoresConfig } from './config-loader.js';

const CONFIG_FILE_NAME = '.wix-stores.yaml';
const ADD_MENU_OUTPUT_REL = 'agent-kit/aiditor/add-menu/wix-stores.yaml';
const ADD_MENU_GENERATED_REL = 'agent-kit/aiditor/add-menu/wix-stores.generated.yaml';

function resolvePackageAgentKitPath(relativePath: string): string {
    const thisDir = path.dirname(fileURLToPath(import.meta.url));
    const fromDist = path.join(thisDir, relativePath);
    if (fs.existsSync(fromDist)) {
        return fromDist;
    }
    return path.join(thisDir, '..', relativePath);
}

function resolveAddMenuTemplatePath(): string {
    return resolvePackageAgentKitPath('agent-kit/aiditor/add-menu.template.yaml');
}

/**
 * Write Add Menu catalog from package template (Design Log #20 W1).
 * Idempotent: skips when output exists unless ctx.force.
 *
 * Q8 note: product-page prompt references agent-kit/materialized-contracts/wix-stores/product-page.jay-contract,
 * which is materialized by the existing wix-stores setup / agent-kit flow (not by this writer).
 */
function writeAddMenuCatalog(ctx: { projectRoot: string; force: boolean }): string | null {
    const outputPath = path.join(ctx.projectRoot, ADD_MENU_OUTPUT_REL);

    if (fs.existsSync(outputPath) && !ctx.force) {
        return null;
    }

    const templatePath = resolveAddMenuTemplatePath();
    const templateContent = fs.readFileSync(templatePath, 'utf-8');

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, templateContent, 'utf-8');

    return ADD_MENU_OUTPUT_REL;
}

/**
 * Write generated Add Menu catalog — one item per indexed category (Design Log #19 M19.2).
 * Regenerated on every successful references run (jay-stack agent-kit).
 */
function writeGeneratedAddMenuCatalog(
    projectRoot: string,
    categoryRoots: CategoryTreeNode[],
): string {
    const outputPath = path.join(projectRoot, ADD_MENU_GENERATED_REL);
    const config = loadWixStoresConfig(projectRoot);
    const items = buildCategoryAddMenuItems(categoryRoots, config);

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    const header =
        '# DO NOT EDIT BY HAND — regenerated by jay-stack agent-kit (wix-stores references)\n\n';
    const body = yaml.dump({ items }, { indent: 2, lineWidth: 120, noRefs: true });
    fs.writeFileSync(outputPath, header + body, 'utf-8');

    return ADD_MENU_GENERATED_REL;
}

const CONFIG_TEMPLATE = `# Wix Stores Configuration
#
# URL templates for link generation.
# Placeholders: {slug} (product), {category} (sub-category), {prefix} (root category)
#
# urls:
#   product: "/products/{slug}"                              # simple (default)
#   product: "/products/{category}/{slug}"                   # with categories
#   product: "/products/{prefix}/{category}/{slug}"          # with prefixes + categories
#   category: "/products/{prefix}/{category}"                # category deep-link pages
#
# Fallback category for pages without category context:
# defaultCategory: "all-products"
#
# To see available categories: jay-stack setup wix-stores (generates category tree reference)

urls:
  product: "/products/{slug}"
`;

export async function setupWixStores(ctx: PluginSetupContext): Promise<PluginSetupResult> {
    if (ctx.initError) {
        return {
            status: 'error',
            message: `Service init failed (is wix-server-client configured?). ${ctx.initError.message}`,
        };
    }

    // Verify the stores service is available
    try {
        getService(WIX_STORES_SERVICE_MARKER);
    } catch {
        return {
            status: 'error',
            message: 'WixStoresService not available. Run setup for wix-server-client first.',
        };
    }

    // Create config template if it doesn't exist
    const configPath = path.join(ctx.configDir, CONFIG_FILE_NAME);
    const configCreated: string[] = [];

    if (!fs.existsSync(configPath)) {
        if (!fs.existsSync(ctx.configDir)) {
            fs.mkdirSync(ctx.configDir, { recursive: true });
        }
        fs.writeFileSync(configPath, CONFIG_TEMPLATE, 'utf-8');
        configCreated.push(`config/${CONFIG_FILE_NAME}`);
    }

    const service = getService(WIX_STORES_SERVICE_MARKER) as WixStoresService;

    try {
        const { searchProducts: searchProductsApi } = await import('./wix-apis/search-products.js');
        await searchProductsApi(service.wixClient, {});
    } catch (e: any) {
        const msg = e.message || '';
        const hint =
            msg.includes('404') || msg.includes('not found')
                ? 'Wix Stores may not be installed on this site'
                : msg.includes('403') || msg.includes('permission')
                  ? 'API key may lack Wix Stores permissions'
                  : 'This package requires the Stores Catalog V3 API — if using Catalog V1, use @jay-framework/wix-stores-v1 instead';
        return {
            status: 'error',
            message: `Wix Stores V3 API check failed: ${hint}. (${msg})`,
        };
    }

    const message = `Wix Stores configured (product URL: ${service.urls.product})`;

    return {
        status: 'configured',
        message,
        ...(configCreated.length > 0 ? { configCreated } : {}),
    };
}

// ============================================================================
// References handler (jay-stack agent-kit) — generate category tree reference
// ============================================================================

interface CategoryNode extends CategoryTreeNode {}

/**
 * Generate a YAML reference file with the full category tree.
 * Shows all categories with IDs, names, product counts, and parent-child hierarchy.
 */
export async function generateWixStoresReferences(
    ctx: PluginReferencesContext,
): Promise<PluginReferencesResult> {
    if (ctx.initError) {
        throw new Error(`init failed: ${ctx.initError.message}`);
    }

    let storesService: WixStoresService;
    try {
        storesService = getService(WIX_STORES_SERVICE_MARKER) as WixStoresService;
    } catch {
        throw new Error('WixStoresService not available. Run jay-stack setup first.');
    }

    fs.mkdirSync(ctx.referencesDir, { recursive: true });

    const referencesCreated: string[] = [];

    const addMenuStatic = writeAddMenuCatalog(ctx);
    if (addMenuStatic) {
        referencesCreated.push(addMenuStatic);
    }
    referencesCreated.push(
        ...copyAiditorAddMenuThumbnails(ctx, resolvePackageAgentKitPath, 'wix-stores'),
    );

    // Fetch all visible categories
    const allCategories: Array<{
        _id?: string;
        name?: string;
        slug?: string;
        itemCounter?: number;
        parentCategory?: { _id?: string };
    }> = [];

    let cursor: string | undefined;
    let hasMore = true;
    while (hasMore) {
        const result = await queryCategoriesApi(
            storesService.wixClient,
            cursor
                ? { cursorPaging: { cursor } }
                : { filter: { visible: true }, cursorPaging: { limit: 100 } },
        );
        allCategories.push(...(result.categories || []));
        cursor = result.pagingMetadata?.cursors?.next;
        hasMore = !!cursor;
    }

    // Build tree structure
    const nodeMap = new Map<string, CategoryNode>();
    for (const cat of allCategories) {
        if (!cat._id) continue;
        nodeMap.set(cat._id, {
            _id: cat._id,
            name: cat.name || '',
            slug: cat.slug || '',
            productCount: cat.itemCounter || 0,
            children: [],
        });
    }

    const roots: CategoryNode[] = [];
    for (const cat of allCategories) {
        if (!cat._id) continue;
        const node = nodeMap.get(cat._id)!;
        const parentId = cat.parentCategory?._id;
        if (parentId && nodeMap.has(parentId)) {
            nodeMap.get(parentId)!.children.push(node);
        } else {
            roots.push(node);
        }
    }

    // Write YAML
    const categoriesPath = path.join(ctx.referencesDir, 'categories.yaml');
    fs.writeFileSync(
        categoriesPath,
        yaml.dump(
            {
                _description:
                    'Wix Stores category tree for agent discovery. Shows category hierarchy, IDs, slugs, product counts, and parent-child relationships.',
                totalCategories: allCategories.length,
                categoryTree: roots,
            },
            { indent: 2, lineWidth: 120, noRefs: true },
        ),
        'utf-8',
    );

    const addMenuGenerated = writeGeneratedAddMenuCatalog(ctx.projectRoot, roots);

    // Fetch and write data extension schemas
    let extensionFieldCount = 0;
    try {
        const extensionSchemas = await storesService.getDataExtensionSchemas();
        const userFieldsSchema = extensionSchemas.find(
            (s: DataExtensionSchema) => s.namespace === '_user_fields',
        );
        const properties = userFieldsSchema?.jsonSchema?.properties as
            | Record<string, { type?: string }>
            | undefined;

        if (properties && Object.keys(properties).length > 0) {
            extensionFieldCount = Object.keys(properties).length;
            const extensionPath = path.join(ctx.referencesDir, 'data-extension-fields.yaml');
            fs.writeFileSync(
                extensionPath,
                yaml.dump(
                    {
                        _description:
                            'Product data extension fields (custom fields defined in Wix dashboard).',
                        fqdn: 'wix.stores.v3.product',
                        namespace: '_user_fields',
                        fieldCount: extensionFieldCount,
                        fields: Object.fromEntries(
                            Object.entries(properties).map(([key, prop]) => [
                                key,
                                { type: prop.type },
                            ]),
                        ),
                    },
                    { indent: 2, lineWidth: 120, noRefs: true },
                ),
                'utf-8',
            );
        }
    } catch (error) {
        console.error('[wix-stores] Failed to fetch data extension schemas:', error);
    }

    referencesCreated.push(
        `agent-kit/references/${ctx.pluginName}/categories.yaml`,
        addMenuGenerated,
    );
    if (extensionFieldCount > 0) {
        referencesCreated.push(`agent-kit/references/${ctx.pluginName}/data-extension-fields.yaml`);
    }

    return {
        referencesCreated,
        message: `${allCategories.length} categories (${roots.length} root), ${extensionFieldCount} extension fields`,
    };
}
