import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

import type { MediaAddMenuItem } from './media-items.js';

export const ADD_MENU_GENERATED_REL = 'agent-kit/aiditor/add-menu/wix-media.generated.yaml';

export function writeGeneratedAddMenuCatalog(
    projectRoot: string,
    items: MediaAddMenuItem[],
): string {
    const outputPath = path.join(projectRoot, ADD_MENU_GENERATED_REL);

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    const header = '# DO NOT EDIT BY HAND — regenerated by wix-media (setup / rebuild-index)\n\n';
    const body = yaml.dump({ items }, { indent: 2, lineWidth: 120, noRefs: true });
    fs.writeFileSync(outputPath, header + body, 'utf-8');

    return ADD_MENU_GENERATED_REL;
}
